name: Test Automation and Quality Gates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
#  schedule:
    # Run daily at 2 AM UTC for continuous monitoring
#    - cron: '0 2 * * *'

env:
  PYTHON_VERSION: '3.12'
  ANSIBLE_MINIMUM_VERSION: '8.0.0'

jobs:
  quality-gates:
    name: Quality Gates and Performance Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible>=${{ env.ANSIBLE_MINIMUM_VERSION }}
        pip install pytest>=7.4.0 pytest-cov pytest-mock pytest-xdist
        pip install requests>=2.31.0 cryptography>=41.0.0
        pip install coverage>=7.3.0 dnspython>=2.4.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi

    - name: Run Test Quality Gates
      run: |
        python scripts/test_quality_gates.py

    - name: Run Performance Validation
      run: |
        python scripts/performance_validation.py

    - name: Upload Quality Gate Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: quality-gate-results
        path: quality_gate_results.json

    - name: Upload Performance Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results
        path: performance_results.json

  unit-tests:
    name: Unit Tests with Coverage
    runs-on: ubuntu-latest
    needs: quality-gates
    timeout-minutes: 8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible>=${{ env.ANSIBLE_MINIMUM_VERSION }}
        pip install pytest>=7.4.0 pytest-cov pytest-mock pytest-xdist
        pip install requests>=2.31.0 cryptography>=41.0.0
        pip install coverage>=7.3.0 dnspython>=2.4.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi

    - name: Run Unit Tests with Coverage
      run: |
        pytest tests/unit/ \
          --cov=plugins.action \
          --cov=plugins.module_utils \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --cov-fail-under=80 \
          --cov-branch \
          -v \
          --tb=short \
          --maxfail=5

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unit-tests
        name: unit-test-coverage
        fail_ci_if_error: true

    - name: Upload Coverage HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-coverage-html
        path: htmlcov/

    - name: Coverage Comment
      if: github.event_name == 'pull_request'
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MINIMUM_GREEN: 80
        MINIMUM_ORANGE: 70

  component-tests:
    name: Component Tests with Coverage
    runs-on: ubuntu-latest
    needs: quality-gates
    timeout-minutes: 8

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible>=${{ env.ANSIBLE_MINIMUM_VERSION }}
        pip install pytest>=7.4.0 pytest-cov pytest-mock pytest-xdist
        pip install requests>=2.31.0 cryptography>=41.0.0
        pip install coverage>=7.3.0 dnspython>=2.4.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi

    - name: Run Component Tests with Coverage
      run: |
        pytest tests/component/ \
          --cov=plugins.action \
          --cov=plugins.module_utils \
          --cov-append \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --cov-branch \
          -v \
          --tb=short \
          --maxfail=5

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: component-tests
        name: component-test-coverage
        fail_ci_if_error: true

    - name: Upload Coverage HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: component-coverage-html
        path: htmlcov/

  parallel-tests:
    name: Parallel Test Execution
    runs-on: ubuntu-latest
    needs: [unit-tests, component-tests]
    timeout-minutes: 6

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible>=${{ env.ANSIBLE_MINIMUM_VERSION }}
        pip install pytest>=7.4.0 pytest-cov pytest-mock pytest-xdist
        pip install requests>=2.31.0 cryptography>=41.0.0
        pip install coverage>=7.3.0 dnspython>=2.4.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi

    - name: Run Full Test Suite in Parallel
      run: |
        pytest \
          -n auto \
          --cov=plugins.action \
          --cov=plugins.module_utils \
          --cov-report=xml \
          --cov-report=term-missing \
          --cov-fail-under=80 \
          --cov-branch \
          -v \
          --tb=short \
          --maxfail=10 \
          --durations=10

    - name: Upload Parallel Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: parallel-tests
        name: parallel-test-coverage
        fail_ci_if_error: true

  coverage-automation:
    name: Coverage Automation
    runs-on: ubuntu-latest
    needs: [unit-tests, component-tests]
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible>=${{ env.ANSIBLE_MINIMUM_VERSION }}
        pip install pytest>=7.4.0 pytest-cov pytest-mock pytest-xdist
        pip install requests>=2.31.0 cryptography>=41.0.0
        pip install coverage>=7.3.0 dnspython>=2.4.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi

    - name: Run Coverage Automation
      run: |
        python scripts/coverage_automation.py

    - name: Upload Coverage JSON
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-json
        path: coverage.json

    - name: Upload Coverage XML
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-xml
        path: coverage.xml

    - name: Coverage Badge
      if: github.ref == 'refs/heads/main'
      uses: 5monkeys/cobertura-action@master
      with:
        path: coverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 80

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run Bandit Security Scan
      run: |
        bandit -r plugins/ -f json -o bandit-report.json || true
        bandit -r plugins/ -f txt

    - name: Run Safety Check
      run: |
        safety check --json --output safety-report.json || true
        safety check

    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  notify-on-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [quality-gates, unit-tests, component-tests, coverage-automation]
    if: failure()

    steps:
    - name: Notify on Failure
      uses: 8398a7/action-slack@v3
      if: github.ref == 'refs/heads/main'
      with:
        status: failure
        channel: '#ci-cd'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        text: |
          Test Automation Failed on main branch
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}

  report-summary:
    name: Generate Test Report Summary
    runs-on: ubuntu-latest
    needs: [quality-gates, unit-tests, component-tests, parallel-tests, coverage-automation]
    if: always()

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4

    - name: Generate Summary Report
      run: |
        echo "# Test Automation Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "- Quality Gates: ${{ needs.quality-gates.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Unit Tests: ${{ needs.unit-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Component Tests: ${{ needs.component-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Parallel Tests: ${{ needs.parallel-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Coverage Automation: ${{ needs.coverage-automation.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Artifacts Generated" >> $GITHUB_STEP_SUMMARY
        echo "- Coverage reports (HTML, XML, JSON)" >> $GITHUB_STEP_SUMMARY
        echo "- Quality gate results" >> $GITHUB_STEP_SUMMARY
        echo "- Performance validation results" >> $GITHUB_STEP_SUMMARY
        echo "- Security scan reports" >> $GITHUB_STEP_SUMMARY
